<div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $block->getBaseUrl().'employemodule/index/save'; ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill The Form Properly')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Employee ID')) ?></span></label>
                            <div class="control">
                                <input name="empid" id="empid" title="empid" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('First Name')) ?></span></label>
                            <div class="control">
                                <input name="fname" id="fname" title="fname" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alpha-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Last Name')) ?></span></label>
                            <div class="control">
                                <input name="lname" id="lname" title="lname" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Email id')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="email" value="" class="input-text"
                                       type="email" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Company Name')) ?></span></label>
                            <div class="control">
                                <input name="company" id="company" title="cname" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Department')) ?></span></label>
                            <div class="control">
                                <input name="department" id="department" title="dept" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Occupation')) ?></span></label>
                            <div class="control">
                                <input name="occupation" id="occupation" title="occupation" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Address')) ?></span></label>
                            <div class="control">
                                <textarea id="address" name="address" title="address" class="" cols=10 rows=10></textarea>
                            </div>
                        </div>

                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Mobile Number')) ?></span></label>
                            <div class="control">
                                <input name="phone" id="phone" title="mobno" value="" class="input-text"
                                       type="number" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Joining Date')) ?></span></label>
                            <div class="control">
                                <input name="doj" id="doj" title="jdate" value="" class="input-text"
                                       type="date" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Date Of Birth')) ?></span></label>
                            <div class="control">
                                <input name="dob" id="dob" title="bdate" value="" class="input-text"
                                       type="date" data-validate="{required:true}">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="reset" title="reset"><span><?= $block->
                        escapeHtmlAttr(__('Reset')) ?></span></button>
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>